### ISSUE TITLE
Remove 32-bit-preference flag

### ISSUE THREAD

**Issue by FacticiusVir** [Aimdrol/WoT-Replay-Analyzer#2]
If I run the app against 3000+ replays, I get a large number of OutOfMemoryExceptions and the viewer does not load. Removing the 32-bit-Preference flag from the executable header using CorFlag allows the app to run 64-bit and all replays load fine.

**Comment by Aimdrol** [comment]
I'll check if this is something I can do by default.

**Comment by Aimdrol** [comment]
Forgot to close this one
