### ISSUE TITLE
Match scores

### ISSUE THREAD

**Issue by Avalon304** [Aimdrol/WoT-Replay-Analyzer#5]
Is it possible for the app to extract the score of a match (ie 15-5) in addition to the outcome (Victory/Defeat).

**Comment by Aimdrol** [comment]
Not at this point.
The score itself is not saved in the json block but can be reconstructed from the amount of deaths for most games. I've put it on my to-do-list.

**Comment by Aimdrol** [comment]
Implemented with ab28372541ca6592f1e229a7737dc4e2f6887c76
